GenChordProgCommon.js: src/GenChordProgCommon.c
	emcc src/GenChordProgCommon.c -o GenChordProgCommon.js -s MODULARIZE -s EXPORTED_FUNCTIONS='["_malloc", "_free"]' -s EXPORTED_RUNTIME_METHODS=ccall,getValue,UTF8ToString
